# Generated by Django 3.2.6 on 2021-09-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(default='', max_length=200)),
                ('xpath', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('page_title', models.CharField(default='', max_length=50)),
                ('popup_title', models.CharField(default='', max_length=50)),
                ('ns_map', models.CharField(default='', max_length=200)),
                ('dropdown_values', models.CharField(default='', max_length=200)),
                ('default_value', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(choices=[('EAD', 'EAD'), ('EBD', 'EBD'), ('OSA', 'OSA'), ('TDM', 'TDM')], default='EAD', max_length=20)),
            ],
        ),
    ]
